version: '3'



services:
  nats-server:
    image: nats:latest
    ports: 
      - "8222:8222"

  client-geteway:
    build: ./client-gateway
    ports:
      - "${CLIENT_GATEWAY_PORT}:3000"
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
    
  products-ms:
    build: ./products-microservice
    ports:
        - "3001:3001"
    volumes:
        - ./products-microservice/src:/usr/src/app/src
    command: npm run docker:start
    environment:
        - PORT=3000
        - NATS_SERVERS=nats://nats-server:4222
        - DATABASE_URL=file:./dev.db

  orders-ms:
    build: ./orders-microservice
    ports:
      - "3002:3002"
    volumes:
      - ./orders-microservice/src:/usr/src/app/src
    command: npm run docker:start
    environment:
      - PORT=3002
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=postgresql://orders:password@orders-db:5432/orders?schema=public
    depends_on:
      - orders-db

  orders-db:
    container_name: orders-db
    image: postgres:16.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: orders
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders
    volumes:
      - ./orders-db:/var/lib/postgresql/data
    